bottle_service_app/authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('account-creation', views.account_creation, name='account_creation'),
]

bottle_service_app/bottle_service_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('distributor/', include('distributor.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('customer/', include('customer.urls')),
    path('administration/', include('administration.urls')),
    path('partners/', include('partners.urls')),
    path('schedule/', include('schedule.urls')),
    path('cart/', include('cart.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bottle_service_app/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add-to-cart/<int:menu_item_id>/', views.add_to_cart,
         name='add_to_cart'),
    path('remove-from-cart/<int:menu_item_id>/', views.remove_from_cart,
         name='remove_from_cart'),
    path('cart/<int:restaurant_id>/', views.cart,
         name='cart'),
    path('checkout/<int:restaurant_id>/', views.checkout,
         name='checkout'),
    path('clear-cart/<int:restaurant_id>/', views.clear_cart,
         name='clear_cart'),
    path('process-payment/<int:restaurant_id>/', views.process_payment,
         name='process_payment'),
    path('order-processed/<int:restaurant_id>/', views.order_processed,
         name='order_processed'),
    path('order-confirmed/<int:restaurant_id>/', views.order_confirmed,
         name='order_confirmed'),
    path('order-rejected/<int:restaurant_id>/', views.order_rejected,
         name='order_rejected'),
    path('order-completed/<int:restaurant_id>/', views.order_completed,
         name='order_completed'),


]

bottle_service_app/customer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.customer_home, name='customer_home'),
    path('customer-restaurant-menu/<int:restaurant_id>/', views.customer_restaurant_menu,
         name='customer_restaurant_menu'),
    path('register-customer-email/<int:restaurant_id>/', views.register_customer_email,
         name='register_customer_email'),
    path('register-customer-verification/<int:restaurant_id>/', views.register_customer_verification,
         name='register_customer_verification'),
    path('register-customer/<int:restaurant_id>/', views.register_customer,
         name='register_customer'),

]

bottle_service_app/customer/models.py
from django.db import models
from django.utils import timezone


class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    last_name = models.CharField(max_length=100, null=True)
    first_name = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True, unique=True)
    created_at = models.DateTimeField(default=timezone.now)
    verified = models.BooleanField(default=False)

bottle_service_app/customer/forms.py
from django import forms

from customer.models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['last_name', 'first_name', 'email']
        

bottle_service_app/customer/views.py
from django.shortcuts import render, redirect

from authentication.decorators import bottle_service_auth
from authentication.enums import BottleServiceAccountType
from authentication.security import VerificationCode
from authentication.session import BottleServiceSession
from customer.forms import CustomerForm
from customer.models import Customer
from partners.menu import customer_menu
from restaurant.models import Restaurant
from schedule.utils import get_current_datetime, is_within_operational_hours


@bottle_service_auth(roles=[BottleServiceAccountType.CUSTOMER])
def customer_home(request):
    return render(request, 'customer/customer_home.html')


def customer_restaurant_menu(request, restaurant_id):
    if request.method == 'GET':
        try:
            restaurant = Restaurant.objects.get(id=restaurant_id)
        except Restaurant.DoesNotExist:
            raise Exception('Restaurant does not exist')
        customer_order = BottleServiceSession.get_customer_order(request, restaurant)
        menu_map = customer_menu(restaurant)
        as_of_time = get_current_datetime()
        menu_open = is_within_operational_hours(restaurant.weekly_schedule, as_of_time)
        if menu_open:
            add_open_status_and_quantity_to_menu_item(menu_map, as_of_time, customer_order)
        return render(request, 'customer/restaurant_customer_menu.html',
                      {'restaurant': restaurant, 'menu_map': menu_map, 'menu_open': menu_open,
                       'as_of_time': as_of_time, 'customer_order': customer_order})


def add_open_status_and_quantity_to_menu_item(menu_map, as_of_time, customer_order):
    distributor_map = dict()
    for category, menu_items in menu_map.items():
        for item in menu_items:
            if item.parent_menu.distributor.id not in distributor_map:
                distributor_map[item.parent_menu.distributor.id] = is_within_operational_hours(
                    item.parent_menu.distributor.weekly_schedule, as_of_time)
            item.item_open = distributor_map[item.parent_menu.distributor.id]
            order_item = customer_order.order_item_by_item(item)
            if order_item is None:
                item.quantity = 0
            else:
                item.quantity = order_item.quantity


def register_customer_email(request, restaurant_id):
    try:
        restaurant = Restaurant.objects.get(id=restaurant_id)
    except Restaurant.DoesNotExist:
        raise Exception('Restaurant does not exist')
    if request.method == 'GET':
        customer_form = CustomerForm()
        return render(request, 'customer/register_customer_email.html', {'restaurant': restaurant,
                                                                   'customer_form': customer_form})
    elif request.method == 'POST':
        customer_form = CustomerForm(request.POST)
        email = customer_form['email'].value()
        verification_code = VerificationCode.generate()
        VerificationCode.store_code(request, verification_code, email)
        VerificationCode.notify_code(request, email, verification_code)
        initial_data = {
                'email': email
            }
        customer_form = CustomerForm(initial=initial_data)
        return render(request, 'customer/register_customer_verification.html',
                      {'restaurant': restaurant, 'customer_form': customer_form})


def register_customer_verification(request, restaurant_id):
    try:
        restaurant = Restaurant.objects.get(id=restaurant_id)
    except Restaurant.DoesNotExist:
        raise Exception('Restaurant does not exist')

    if request.method == 'POST':
        verification_code = request.POST.get('verification_code')
        customer_form = CustomerForm(request.POST)
        email = customer_form['email'].value()
        if not VerificationCode.check_code(request, verification_code, email):
            initial_data = {
                'email': email
            }
            customer_form = CustomerForm(initial=initial_data)
            return render(request, 'customer/register_customer_verification.html',
                          {'restaurant': restaurant, 'customer_form': customer_form,
                           'error': 'Invalid verification code'})
        try:
            customer = Customer.objects.filter(email=email).first()
        except Customer.DoesNotExist:
            customer = None

        if customer and customer.verified:
            customer_order = BottleServiceSession.get_customer_order(request, restaurant)
            customer_order.customer = customer
            customer_order.save()
            # TODO: Send email to with a verification link or code to verify email of verified customer
            return redirect(f'/cart/checkout/{restaurant_id}/')
        else:
            initial_data = {
                'email': email
            }
            customer_form = CustomerForm(initial=initial_data)
            return render(request, 'customer/register_customer.html', {'restaurant': restaurant,
                                                                       'customer_form': customer_form})


def register_customer(request, restaurant_id):
    try:
        restaurant = Restaurant.objects.get(id=restaurant_id)
    except Restaurant.DoesNotExist:
        raise Exception('Restaurant does not exist')
    if request.method == 'POST':
        customer_order = BottleServiceSession.get_customer_order(request, restaurant)
        customer_form = CustomerForm(request.POST)

        email = customer_form['email'].value()
        last_name = customer_form['last_name'].value()
        first_name = customer_form['first_name'].value()
        if last_name is None or first_name is None or email is None:
            customer_form = CustomerForm()
            return render(request, 'customer/register_customer_email.html', {'restaurant': restaurant,
                                                                             'customer_form': customer_form,
                                                                             'errors': 'Missing required fields'})
        try:
            customer = Customer.objects.filter(email=email).first()
        except Customer.DoesNotExist:
            customer = None
        if customer and customer.verified:
            raise Exception('Customer already verified')
        if customer:
            customer.last_name = last_name
            customer.first_name = first_name
            customer.verified = True
            customer.save()
        else:
            customer = Customer(email=email, last_name=last_name, first_name=first_name)
            customer.verified = True
            customer.save()

        customer_order.customer = customer
        customer_order.save()
        # TODO: Send email to with a verification link or code to verify email
        return redirect(f'/cart/checkout/{restaurant_id}/')
    # Error if request is not GET or POST
    raise Exception('Invalid request')

bottle_service_app/customer/templates/customer/customer_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer</title>
</head>
<body>
    <h1>Customer</h1>
    <a href="{% url 'authentication:logout' %}">Logout</a>
</body>
</html>

bottle_service_app/customer/templates/customer/register_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Profile</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 20px;
            padding: 20px;
            background-color: #f8f8f8;
        }

        h2 {
            color: #333;
        }

        form {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input, textarea {
            width: 100%;
            padding: 8px;
            margin-bottom: 12px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }

        button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .error {
            color: red;
        }
    </style>
</head>
<body>
    <h2>Customer Profile</h2>
    <div class="error">{{ customer_form.errors }}</div>
    <form action="{% url 'register_customer' restaurant.id %}" method="post">
        {% csrf_token %}

        <label for="{{ customer_form.email.id_for_label }}">Email:</label>
        <input type="text" name="email_display" value="{{ customer_form.email.value }}" required id="id_email" disabled>
        <input type="hidden" name="email" value="{{ customer_form.email.value }}">

        <label for="{{ customer_form.last_name.id_for_label }}">Last Name:</label>
        {{ customer_form.last_name }}

        <label for="{{ customer_form.first_name.id_for_label }}">First Name:</label>
        {{ customer_form.first_name }}

        <button type="submit">Submit</button>
        <a href="{% url 'customer_restaurant_menu' restaurant.id %}">Cancel</a>
    </form>
</body>
</html>

bottle_service_app/customer/templates/customer/register_customer_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Profile - Email</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 20px;
            padding: 20px;
            background-color: #f8f8f8;
        }

        h2 {
            color: #333;
        }

        form {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input, textarea {
            width: 100%;
            padding: 8px;
            margin-bottom: 12px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }

        button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .error {
            color: red;
        }
    </style>
</head>
<body>
    <h2>Customer Profile - Email</h2>
    <div class="error">{{ customer_form.errors }}</div>
    <form method="post">
        {% csrf_token %}

        <label for="{{ customer_form.email.id_for_label }}">Email:</label>
        {{ customer_form.email }}

        <button type="submit">Submit</button>
        <a href="{% url 'customer_restaurant_menu' restaurant.id %}">Cancel</a>
    </form>
</body>
</html>

bottle_service_app/customer/templates/customer/register_customer_verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Profile - Email</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 20px;
            padding: 20px;
            background-color: #f8f8f8;
        }

        h2 {
            color: #333;
        }

        form {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input, textarea {
            width: 100%;
            padding: 8px;
            margin-bottom: 12px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }

        button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .error {
            color: red;
        }
    </style>
</head>
<body>
    <h2>Customer Profile - Verification</h2>
    <h3>Check you email for verification code</h3>
    <div class="error">{{ error }}</div>
    <form action="{% url 'register_customer_verification' restaurant.id %}" method="post">
        {% csrf_token %}

        <label for="id_verification">Verification Code:</label>
        <input type="text" name="verification_code" value="" required id="id_verification">
        <input type="hidden" name="email" value="{{ customer_form.email.value }}">

        <button type="submit">Submit</button>
        <a href="{% url 'customer_restaurant_menu' restaurant.id %}">Cancel</a>
    </form>
</body>
</html>

bottle_service_app/customer/templates/customer/restaurant_customer_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ restaurant.name }} Menu</title>
    <style>
        .inline {
          display: inline-block;
        }

        body {
            font-family: 'Arial', sans-serif;
            margin: 20px;
            padding: 20px;
            background-color: #f8f8f8;
        }

        h1 {
            color: #333;
        }

        td {
        padding-right: 50px;
        }

        p {
            margin-bottom: 1px;
        }

        ol {
            margin-bottom: 1px;
        }

        li {
            list-style-type: none;
        }

        form {
            margin-bottom: 0px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }


        button {
            padding: 5px;
            background-color: #007BFF;
            color: #fff;
            border: none;
            cursor: pointer;
        }


        .big_button {
            padding: 10px;
            background-color: #007BFF;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        a {
            text-decoration: none;
            color: #007BFF;
            margin-right: 10px;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h1>{{ restaurant.name }} Menu</h1>
    <h3>{{ as_of_time | date:"l, M. j, Y, g:i a" }} <a href="{{ request.path }}">Refresh</a></h3>
    {% if menu_open %}
    <h4>Total: ${{ customer_order.total_cost }}</h4>
    <p><a href="{% url 'cart' restaurant.id %}">Cart</a></p>
    {% endif %}
    {% if menu_open %}
    <h4>This menu is open.</h4>
    {% else %}
    <h4 style="color: red;">Menu is closed. Please check back later.</h4>
    {% endif %}

    {% if menu_map %}
            <table>
    {% for section, items in menu_map.items %}
                <tr>
    <th colspan="3">{{ section.name }}</th>
                </tr>
    <ol>
        {% for menu_item in items %}
        <li>
                <tr>
                    <td title="{{ item.item.description }}">
                    {{ menu_item.item.name }} {{ menu_item.quantity }}
                    </td>
                    <td>
                    ${{ menu_item.calculated_price }}
                    </td>
                    <td>
                    {{ menu_item.parent_menu.distributor.name }}
                    </td>
                    <td>
                        {% if menu_item.item.out_of_stock %}
                            <div class="inline" style="margin-right: 10px;">
                                <span style="color: red;">OUT OF STOCK</span>
                            </div>
                        {% endif %}
                    </td>
                        {% if menu_open and menu_item.item_open %}
                            {% if customer_order.distributor is None or menu_item.item.distributor == customer_order.distributor %}
                                <td>
                                    <a href="{% url 'add_to_cart' menu_item.id %}">Add To Cart</a>
                                </td>
                                <td>
                                    <a href="{% url 'remove_from_cart' menu_item.id %}">Remove From Cart</a>
                                </td>
                            {% else %}
                                <td colspan="2"></td>
                            {% endif %}
                        {% else %}
                            <td>
                                <div class="inline" style="margin-right: 10px;">
                                    <span style="color: red;">NOT AVAILABLE AT THIS TIME</span>
                                </div>
                            </td>
                        {% endif %}
                </tr>
        </li>
        {% endfor %}
    </ol>
    {% endfor %}
            </table>
    {% else %}
    <p>No menu items found.</p>
    {% endif %}

</body>
</html>